import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class TricycleFarePeta {
    // Helper class to return both distance and validroute. Private is a private modifier, accessible within enclosing class.
    private static class DistanceResult {
        double distance;
        boolean validRoute;
    }
    // Global distance map
    private static final Map<String, Map<String, Double>> DISTANCES = new HashMap<>();
    static {
        // -------- BAGUMBAYAN --------
        Map<String, Double> bagumbayan = new HashMap<>();
        bagumbayan.put("bagumbayan", 0.0);
        bagumbayan.put("bambang", 2.2);
        bagumbayan.put("calzada", 3.6);
        bagumbayan.put("cembo", 1.4);
        bagumbayan.put("central bicutan", 1.4);
        bagumbayan.put("central signal village", 1.6);
        bagumbayan.put("comembo", 3.8);
        bagumbayan.put("east rembo", 3.4);
        bagumbayan.put("fort bonifacio", 1.9);
        bagumbayan.put("hagonoy", 2.9);
        bagumbayan.put("ibayo-tipas", 3.7);
        bagumbayan.put("katuparan", 2.5);
        bagumbayan.put("ligid-tipas", 0.8);
        bagumbayan.put("lower bicutan", 2.0);
        bagumbayan.put("maharlika village", 4.0);
        bagumbayan.put("napindan", 3.5);
        bagumbayan.put("new lower bicutan", 1.4);
        bagumbayan.put("north daang hari", 2.7);
        bagumbayan.put("north signal village", 3.7);
        bagumbayan.put("northside", 2.6);
        bagumbayan.put("palingon", 2.3);
        bagumbayan.put("pembo", 1.5);
        bagumbayan.put("pinagsama", 1.3);
        bagumbayan.put("pitogo", 1.9);
        bagumbayan.put("rizal", 3.4);
        bagumbayan.put("san miguel", 2.7);
        bagumbayan.put("santa ana", 2.5);
        bagumbayan.put("south cembo", 1.0);
        bagumbayan.put("south daang hari", 3.5);
        bagumbayan.put("south signal village", 3.1);
        bagumbayan.put("southside", 2.9);
        bagumbayan.put("tanyag", 3.3);
        bagumbayan.put("tuktukan", 1.8);
        bagumbayan.put("upper bicutan", 1.2);
        bagumbayan.put("ususan", 1.3);
        bagumbayan.put("wawa", 3.7);
        bagumbayan.put("west rembo", 1.7);
        bagumbayan.put("western bicutan", 1.8);
        DISTANCES.put("bagumbayan", bagumbayan);
        // -------- BAMBANG --------
    Map<String, Double> bambang = new HashMap<>();
    bambang.put("bagumbayan", 2.2);
    bambang.put("bambang", 0.0);
    bambang.put("calzada", 3.2);
    bambang.put("cembo", 3.2);
    bambang.put("central bicutan", 0.7);
    bambang.put("central signal village", 3.5);
    bambang.put("comembo", 1.7);
    bambang.put("east rembo", 3.0);
    bambang.put("fort bonifacio", 1.9);
    bambang.put("hagonoy", 1.9);
    bambang.put("ibayo-tipas", 2.0);
    bambang.put("katuparan", 2.2);
    bambang.put("ligid-tipas", 1.5);
    bambang.put("lower bicutan", 2.4);
    bambang.put("maharlika village", 2.5);
    bambang.put("napindan", 1.9);
    bambang.put("new lower bicutan", 3.3);
    bambang.put("north daang hari", 1.4);
    bambang.put("north signal village", 2.9);
    bambang.put("northside", 0.7);
    bambang.put("palingon", 2.7);
    bambang.put("pembo", 3.4);
    bambang.put("pinagsama", 2.1);
    bambang.put("pitogo", 1.9);
    bambang.put("rizal", 2.0);
    bambang.put("san miguel", 1.3);
    bambang.put("santa ana", 1.6);
    bambang.put("south cembo", 1.5);
    bambang.put("south daang hari", 3.3);
    bambang.put("south signal village", 3.3);
    bambang.put("southside", 2.1);
    bambang.put("tanyag", 1.1);
    bambang.put("tuktukan", 2.0);
    bambang.put("upper bicutan", 2.8);
    bambang.put("ususan", 3.4);
    bambang.put("wawa", 1.7);
    bambang.put("west rembo", 3.3);
    bambang.put("western bicutan", 0.6);
    DISTANCES.put("bambang", bambang);
    // -------- CALZADA --------
    Map<String, Double> calzada = new HashMap<>();
    calzada.put("bagumbayan", 3.6);
    calzada.put("bambang", 3.2);
    calzada.put("calzada", 0.0);
    calzada.put("cembo", 3.1);
    calzada.put("central bicutan", 3.1);
    calzada.put("central signal village", 3.6);
    calzada.put("comembo", 3.0);
    calzada.put("east rembo", 0.2);
    calzada.put("fort bonifacio", 1.7);
    calzada.put("hagonoy", 1.4);
    calzada.put("ibayo-tipas", 2.0);
    calzada.put("katuparan", 1.1);
    calzada.put("ligid-tipas", 3.0);
    calzada.put("lower bicutan", 1.6);
    calzada.put("maharlika village", 2.0);
    calzada.put("napindan", 2.0);
    calzada.put("new lower bicutan", 3.4);
    calzada.put("north daang hari", 4.6);
    calzada.put("north signal village", 0.7);
    calzada.put("northside", 2.6);
    calzada.put("palingon", 1.5);
    calzada.put("pembo", 3.3);
    calzada.put("pinagsama", 2.2);
    calzada.put("pitogo", 1.7);
    calzada.put("rizal", 1.7);
    calzada.put("san miguel", 4.5);
    calzada.put("santa ana", 4.7);
    calzada.put("south cembo", 3.8);
    calzada.put("south daang hari", 0.3);
    calzada.put("south signal village", 0.9);
    calzada.put("southside", 1.1);
    calzada.put("tanyag", 3.1);
    calzada.put("tuktukan", 1.8);
    calzada.put("upper bicutan", 2.8);
    calzada.put("ususan", 3.6);
    calzada.put("wawa", 2.7);
    calzada.put("west rembo", 2.9);
    calzada.put("western bicutan", 3.5);
    DISTANCES.put("calzada", calzada);
    // -------- CEMBO --------
    Map<String, Double> cembo = new HashMap<>();
    cembo.put("bagumbayan", 1.4);
    cembo.put("bambang", 3.2);
    cembo.put("calzada", 3.1);
    cembo.put("cembo", 0.0);
    cembo.put("central bicutan", 2.5);
    cembo.put("central signal village", 0.5);
    cembo.put("comembo", 4.4);
    cembo.put("east rembo", 3.0);
    cembo.put("fort bonifacio", 1.8);
    cembo.put("hagonoy", 3.0);
    cembo.put("ibayo-tipas", 4.0);
    cembo.put("katuparan", 2.4);
    cembo.put("ligid-tipas", 1.8);
    cembo.put("lower bicutan", 1.6);
    cembo.put("maharlika village", 4.3);
    cembo.put("napindan", 3.9);
    cembo.put("new lower bicutan", 0.4);
    cembo.put("north daang hari", 4.0);
    cembo.put("north signal village", 3.5);
    cembo.put("northside", 3.3);
    cembo.put("palingon", 1.6);
    cembo.put("pembo", 0.2);
    cembo.put("pinagsama", 1.2);
    cembo.put("pitogo", 1.9);
    cembo.put("rizal", 3.6);
    cembo.put("san miguel", 4.1);
    cembo.put("santa ana", 3.9);
    cembo.put("south cembo", 2.4);
    cembo.put("south daang hari", 2.9);
    cembo.put("south signal village", 2.3);
    cembo.put("southside", 3.0);
    cembo.put("tanyag", 4.1);
    cembo.put("tuktukan", 1.7);
    cembo.put("upper bicutan", 0.5);
    cembo.put("ususan", 0.5);
    cembo.put("wawa", 4.3);
    cembo.put("west rembo", 0.3);
    cembo.put("western bicutan", 2.9);
    DISTANCES.put("cembo", cembo);
    // -------- CENTRAL BICUTAN --------
Map<String, Double> centralBicutan = new HashMap<>();
centralBicutan.put("bagumbayan", 1.4);
centralBicutan.put("bambang", 0.7);
centralBicutan.put("calzada", 3.1);
centralBicutan.put("cembo", 2.5);
centralBicutan.put("central bicutan", 0.0);
centralBicutan.put("central signal village", 2.8);
centralBicutan.put("comembo", 2.4);
centralBicutan.put("east rembo", 2.9);
centralBicutan.put("fort bonifacio", 1.5);
centralBicutan.put("hagonoy", 1.9);
centralBicutan.put("ibayo-tipas", 2.5);
centralBicutan.put("katuparan", 2.0);
centralBicutan.put("ligid-tipas", 0.7);
centralBicutan.put("lower bicutan", 2.0);
centralBicutan.put("maharlika village", 2.9);
centralBicutan.put("napindan", 2.3);
centralBicutan.put("new lower bicutan", 2.6);
centralBicutan.put("north daang hari", 1.7);
centralBicutan.put("north signal village", 2.9);
centralBicutan.put("northside", 1.2);
centralBicutan.put("palingon", 2.3);
centralBicutan.put("pembo", 2.7);
centralBicutan.put("pinagsama", 1.5);
centralBicutan.put("pitogo", 1.5);
centralBicutan.put("rizal", 2.3);
centralBicutan.put("san miguel", 1.7);
centralBicutan.put("santa ana", 1.7);
centralBicutan.put("south cembo", 0.9);
centralBicutan.put("south daang hari", 3.2);
centralBicutan.put("south signal village", 3.0);
centralBicutan.put("southside", 2.1);
centralBicutan.put("tanyag", 1.8);
centralBicutan.put("tuktukan", 1.6);
centralBicutan.put("upper bicutan", 2.1);
centralBicutan.put("ususan", 2.6);
centralBicutan.put("wawa", 2.3);
centralBicutan.put("west rembo", 2.7);
centralBicutan.put("western bicutan", 0.5);
DISTANCES.put("central bicutan", centralBicutan);
// -------- CENTRAL SIGNAL VILLAGE --------
Map<String, Double> centralSignalVillage = new HashMap<>();
centralSignalVillage.put("bagumbayan", 1.6);
centralSignalVillage.put("bambang", 3.5);
centralSignalVillage.put("calzada", 3.6);
centralSignalVillage.put("cembo", 0.5);
centralSignalVillage.put("central bicutan", 2.8);
centralSignalVillage.put("central signal village", 0.0);
centralSignalVillage.put("comembo", 4.9);
centralSignalVillage.put("east rembo", 3.5);
centralSignalVillage.put("fort bonifacio", 2.3);
centralSignalVillage.put("hagonoy", 3.4);
centralSignalVillage.put("ibayo-tipas", 4.4);
centralSignalVillage.put("katuparan", 2.9);
centralSignalVillage.put("ligid-tipas", 2.1);
centralSignalVillage.put("lower bicutan", 2.1);
centralSignalVillage.put("maharlika village", 4.7);
centralSignalVillage.put("napindan", 4.3);
centralSignalVillage.put("new lower bicutan", 0.2);
centralSignalVillage.put("north daang hari", 4.2);
centralSignalVillage.put("north signal village", 4.0);
centralSignalVillage.put("northside", 3.7);
centralSignalVillage.put("palingon", 2.1);
centralSignalVillage.put("pembo", 0.3);
centralSignalVillage.put("pinagsama", 1.7);
centralSignalVillage.put("pitogo", 2.3);
centralSignalVillage.put("rizal", 4.1);
centralSignalVillage.put("san miguel", 4.3);
centralSignalVillage.put("santa ana", 4.1);
centralSignalVillage.put("south cembo", 2.6);
centralSignalVillage.put("south daang hari", 3.4);
centralSignalVillage.put("south signal village", 2.8);
centralSignalVillage.put("southside", 3.4);
centralSignalVillage.put("tanyag", 4.4);
centralSignalVillage.put("tuktukan", 2.2);
centralSignalVillage.put("upper bicutan", 0.9);
centralSignalVillage.put("ususan", 0.2);
centralSignalVillage.put("wawa", 4.7);
centralSignalVillage.put("west rembo", 0.7);
centralSignalVillage.put("western bicutan", 3.2);
DISTANCES.put("central signal village", centralSignalVillage);
// -------- COMEMBO --------
Map<String, Double> comembo = new HashMap<>();
comembo.put("bagumbayan", 3.8);
comembo.put("bambang", 1.7);
comembo.put("calzada", 3.0);
comembo.put("cembo", 4.4);
comembo.put("central bicutan", 2.4);
comembo.put("central signal village", 4.9);
comembo.put("comembo", 0.0);
comembo.put("east rembo", 2.9);
comembo.put("fort bonifacio", 2.7);
comembo.put("hagonoy", 1.8);
comembo.put("ibayo-tipas", 1.0);
comembo.put("katuparan", 2.5);
comembo.put("ligid-tipas", 3.0);
comembo.put("lower bicutan", 3.1);
comembo.put("maharlika village", 1.3);
comembo.put("napindan", 1.0);
comembo.put("new lower bicutan", 4.6);
comembo.put("north daang hari", 2.6);
comembo.put("north signal village", 2.4);
comembo.put("northside", 1.2);
comembo.put("palingon", 3.4);
comembo.put("pembo", 4.6);
comembo.put("pinagsama", 3.2);
comembo.put("pitogo", 2.7);
comembo.put("rizal", 1.3);
comembo.put("san miguel", 2.5);
comembo.put("santa ana", 3.0);
comembo.put("south cembo", 3.2);
comembo.put("south daang hari", 3.3);
comembo.put("south signal village", 3.5);
comembo.put("southside", 2.0);
comembo.put("tanyag", 0.6);
comembo.put("tuktukan", 2.8);
comembo.put("upper bicutan", 4.0);
comembo.put("ususan", 4.7);
comembo.put("wawa", 0.3);
comembo.put("west rembo", 4.5);
comembo.put("western bicutan", 2.3);
DISTANCES.put("comembo", comembo);
// -------- EAST REMBO --------
Map<String, Double> eastRembo = new HashMap<>();
eastRembo.put("bagumbayan", 3.4);
eastRembo.put("bambang", 3.0);
eastRembo.put("calzada", 0.2);
eastRembo.put("cembo", 3.0);
eastRembo.put("central bicutan", 2.9);
eastRembo.put("central signal village", 3.5);
eastRembo.put("comembo", 2.9);
eastRembo.put("east rembo", 0.0);
eastRembo.put("fort bonifacio", 1.6);
eastRembo.put("hagonoy", 1.2);
eastRembo.put("ibayo-tipas", 1.9);
eastRembo.put("katuparan", 0.9);
eastRembo.put("ligid-tipas", 2.9);
eastRembo.put("lower bicutan", 1.4);
eastRembo.put("maharlika village", 1.9);
eastRembo.put("napindan", 1.9);
eastRembo.put("new lower bicutan", 3.3);
eastRembo.put("north daang hari", 4.4);
eastRembo.put("north signal village", 0.7);
eastRembo.put("northside", 2.5);
eastRembo.put("palingon", 1.4);
eastRembo.put("pembo", 3.2);
eastRembo.put("pinagsama", 2.1);
eastRembo.put("pitogo", 1.6);
eastRembo.put("rizal", 1.6);
eastRembo.put("san miguel", 4.3);
eastRembo.put("santa ana", 4.5);
eastRembo.put("south cembo", 3.7);
eastRembo.put("south daang hari", 0.4);
eastRembo.put("south signal village", 0.9);
eastRembo.put("southside", 1.0);
eastRembo.put("tanyag", 3.0);
eastRembo.put("tuktukan", 1.6);
eastRembo.put("upper bicutan", 2.7);
eastRembo.put("ususan", 3.5);
eastRembo.put("wawa", 2.6);
eastRembo.put("west rembo", 2.8);
eastRembo.put("western bicutan", 3.3);
DISTANCES.put("east rembo", eastRembo);
// -------- FORT BONIFACIO --------
Map<String, Double> fortBonifacio = new HashMap<>();
fortBonifacio.put("bagumbayan", 1.9);
fortBonifacio.put("bambang", 1.9);
fortBonifacio.put("calzada", 1.7);
fortBonifacio.put("cembo", 1.8);
fortBonifacio.put("central bicutan", 1.5);
fortBonifacio.put("central signal village", 2.3);
fortBonifacio.put("comembo", 2.7);
fortBonifacio.put("east rembo", 1.6);
fortBonifacio.put("fort bonifacio", 0.0);
fortBonifacio.put("hagonoy", 1.2);
fortBonifacio.put("ibayo-tipas", 2.1);
fortBonifacio.put("katuparan", 0.7);
fortBonifacio.put("ligid-tipas", 1.3);
fortBonifacio.put("lower bicutan", 0.5);
fortBonifacio.put("maharlika village", 2.4);
fortBonifacio.put("napindan", 2.0);
fortBonifacio.put("new lower bicutan", 2.1);
fortBonifacio.put("north daang hari", 3.2);
fortBonifacio.put("north signal village", 1.8);
fortBonifacio.put("northside", 1.7);
fortBonifacio.put("palingon", 0.8);
fortBonifacio.put("pembo", 2.0);
fortBonifacio.put("pinagsama", 0.6);
fortBonifacio.put("pitogo", 0.0);
fortBonifacio.put("rizal", 1.8);
fortBonifacio.put("san miguel", 3.1);
fortBonifacio.put("santa ana", 3.2);
fortBonifacio.put("south cembo", 1.7);
fortBonifacio.put("south signal village", 1.4);
fortBonifacio.put("southside", 1.2);
fortBonifacio.put("tanyag", 2.4);
fortBonifacio.put("tuktukan", 0.1);
fortBonifacio.put("upper bicutan", 1.4);
fortBonifacio.put("ususan", 2.2);
fortBonifacio.put("wawa", 2.5);
fortBonifacio.put("west rembo", 1.8);
fortBonifacio.put("western bicutan", 2.0);
DISTANCES.put("fort bonifacio", fortBonifacio);
// -------- HAGONOY --------
Map<String, Double> hagonoy = new HashMap<>();
hagonoy.put("bagumbayan", 2.9);
hagonoy.put("bambang", 1.9);
hagonoy.put("calzada", 1.4);
hagonoy.put("cembo", 3.0);
hagonoy.put("central bicutan", 1.9);
hagonoy.put("central signal village", 3.4);
hagonoy.put("comembo", 1.8);
hagonoy.put("east rembo", 1.2);
hagonoy.put("fort bonifacio", 1.2);
hagonoy.put("hagonoy", 0.0);
hagonoy.put("ibayo-tipas", 1.0);
hagonoy.put("katuparan", 0.7);
hagonoy.put("ligid-tipas", 2.1);
hagonoy.put("lower bicutan", 1.4);
hagonoy.put("maharlika village", 1.3);
hagonoy.put("napindan", 0.9);
hagonoy.put("new lower bicutan", 3.3);
hagonoy.put("north daang hari", 3.2);
hagonoy.put("north signal village", 1.0);
hagonoy.put("northside", 1.3);
hagonoy.put("palingon", 1.6);
hagonoy.put("pembo", 3.2);
hagonoy.put("pinagsama", 1.8);
hagonoy.put("pitogo", 1.1);
hagonoy.put("rizal", 0.7);
hagonoy.put("san miguel", 3.2);
hagonoy.put("santa ana", 3.4);
hagonoy.put("south cembo", 2.8);
hagonoy.put("south daang hari", 1.6);
hagonoy.put("south signal village", 1.7);
hagonoy.put("southside", 0.2);
hagonoy.put("tanyag", 1.8);
hagonoy.put("tuktukan", 1.3);
hagonoy.put("upper bicutan", 2.6);
hagonoy.put("ususan", 3.4);
hagonoy.put("wawa", 1.6);
hagonoy.put("west rembo", 2.9);
hagonoy.put("western bicutan", 2.2);
DISTANCES.put("hagonoy", hagonoy);
// -------- IBAYO-TIPAS --------
Map<String, Double> ibayoTipas = new HashMap<>();
ibayoTipas.put("bagumbayan", 3.7);
ibayoTipas.put("bambang", 2.0);
ibayoTipas.put("calzada", 2.0);
ibayoTipas.put("cembo", 4.0);
ibayoTipas.put("central bicutan", 2.5);
ibayoTipas.put("central signal village", 4.4);
ibayoTipas.put("comembo", 1.0);
ibayoTipas.put("east rembo", 1.9);
ibayoTipas.put("fort bonifacio", 2.1);
ibayoTipas.put("hagonoy", 1.0);
ibayoTipas.put("ibayo-tipas", 0.0);
ibayoTipas.put("katuparan", 1.7);
ibayoTipas.put("ligid-tipas", 2.9);
ibayoTipas.put("lower bicutan", 2.4);
ibayoTipas.put("maharlika village", 0.4);
ibayoTipas.put("napindan", 0.1);
ibayoTipas.put("new lower bicutan", 4.2);
ibayoTipas.put("north daang hari", 3.3);
ibayoTipas.put("north signal village", 1.4);
ibayoTipas.put("northside", 1.3);
ibayoTipas.put("palingon", 2.7);
ibayoTipas.put("pembo", 4.2);
ibayoTipas.put("pinagsama", 2.7);
ibayoTipas.put("pitogo", 2.1);
ibayoTipas.put("rizal", 0.3);
ibayoTipas.put("san miguel", 3.2);
ibayoTipas.put("santa ana", 3.6);
ibayoTipas.put("south cembo", 3.4);
ibayoTipas.put("south daang hari", 2.3);
ibayoTipas.put("south signal village", 2.6);
ibayoTipas.put("southside", 1.1);
ibayoTipas.put("tanyag", 1.3);
ibayoTipas.put("tuktukan", 2.3);
ibayoTipas.put("upper bicutan", 3.5);
ibayoTipas.put("ususan", 4.4);
ibayoTipas.put("wawa", 0.8);
ibayoTipas.put("west rembo", 4.0);
ibayoTipas.put("western bicutan", 2.6);
DISTANCES.put("ibayo-tipas", ibayoTipas);
// -------- KATUPARAN --------
Map<String, Double> katuparan = new HashMap<>();
katuparan.put("bagumbayan", 2.5);
katuparan.put("bambang", 2.2);
katuparan.put("calzada", 1.1);
katuparan.put("cembo", 2.4);
katuparan.put("central bicutan", 2.0);
katuparan.put("central signal village", 2.9);
katuparan.put("comembo", 2.5);
katuparan.put("east rembo", 0.9);
katuparan.put("fort bonifacio", 0.7);
katuparan.put("hagonoy", 0.7);
katuparan.put("ibayo-tipas", 1.7);
katuparan.put("katuparan", 0.0);
katuparan.put("ligid-tipas", 1.9);
katuparan.put("lower bicutan", 0.8);
katuparan.put("maharlika village", 1.9);
katuparan.put("napindan", 1.6);
katuparan.put("new lower bicutan", 2.7);
katuparan.put("north daang hari", 3.5);
katuparan.put("north signal village", 1.2);
katuparan.put("northside", 1.8);
katuparan.put("palingon", 0.9);
katuparan.put("pembo", 2.6);
katuparan.put("pinagsama", 1.3);
katuparan.put("pitogo", 0.7);
katuparan.put("rizal", 1.4);
katuparan.put("san miguel", 3.5);
katuparan.put("santa ana", 3.7);
katuparan.put("south cembo", 2.8);
katuparan.put("south daang hari", 1.2);
katuparan.put("south signal village", 1.1);
katuparan.put("southside", 0.6);
katuparan.put("tanyag", 2.4);
katuparan.put("tuktukan", 0.8);
katuparan.put("upper bicutan", 2.0);
katuparan.put("ususan", 2.8);
katuparan.put("wawa", 2.2);
katuparan.put("west rembo", 2.3);
katuparan.put("western bicutan", 2.4);
DISTANCES.put("katuparan", katuparan);
// -------- LIGID-TIPAS --------
Map<String, Double> ligidTipas = new HashMap<>();
ligidTipas.put("bagumbayan", 0.8);
ligidTipas.put("bambang", 1.5);
ligidTipas.put("calzada", 3.0);
ligidTipas.put("cembo", 1.8);
ligidTipas.put("central bicutan", 0.7);
ligidTipas.put("central signal village", 2.1);
ligidTipas.put("comembo", 3.0);
ligidTipas.put("east rembo", 2.9);
ligidTipas.put("fort bonifacio", 1.3);
ligidTipas.put("hagonoy", 2.1);
ligidTipas.put("ibayo-tipas", 2.9);
ligidTipas.put("katuparan", 1.9);
ligidTipas.put("ligid-tipas", 0.0);
ligidTipas.put("lower bicutan", 1.6);
ligidTipas.put("maharlika village", 3.2);
ligidTipas.put("napindan", 2.7);
ligidTipas.put("new lower bicutan", 1.9);
ligidTipas.put("north daang hari", 2.3);
ligidTipas.put("north signal village", 3.0);
ligidTipas.put("northside", 1.8);
ligidTipas.put("palingon", 1.9);
ligidTipas.put("pembo", 1.9);
ligidTipas.put("pinagsama", 1.0);
ligidTipas.put("pitogo", 1.3);
ligidTipas.put("rizal", 2.6);
ligidTipas.put("san miguel", 2.3);
ligidTipas.put("santa ana", 2.2);
ligidTipas.put("south cembo", 0.9);
ligidTipas.put("south daang hari", 3.0);
ligidTipas.put("south signal village", 2.7);
ligidTipas.put("southside", 2.2);
ligidTipas.put("tanyag", 2.5);
ligidTipas.put("tuktukan", 1.3);
ligidTipas.put("upper bicutan", 1.4);
ligidTipas.put("ususan", 1.9);
ligidTipas.put("wawa", 2.9);
ligidTipas.put("west rembo", 2.0);
ligidTipas.put("western bicutan", 1.1);
DISTANCES.put("ligid-tipas", ligidTipas);
// -------- LOWER BICUTAN --------
        Map<String, Double> lowerBicutan = new HashMap<>();
        lowerBicutan.put("bagumbayan", 2.0);
        lowerBicutan.put("bambang", 2.4);
        lowerBicutan.put("calzada", 1.6);
        lowerBicutan.put("cembo", 1.6);
        lowerBicutan.put("central bicutan", 2.0);
        lowerBicutan.put("central signal village", 2.1);
        lowerBicutan.put("comembo", 3.1);
        lowerBicutan.put("east rembo", 1.4);
        lowerBicutan.put("fort bonifacio", 0.5);
        lowerBicutan.put("hagonoy", 1.4);
        lowerBicutan.put("ibayo-tipas", 2.4);
        lowerBicutan.put("katuparan", 0.8);
        lowerBicutan.put("ligid-tipas", 1.6);
        lowerBicutan.put("lower bicutan", 0.0);
        lowerBicutan.put("maharlika village", 2.7);
        lowerBicutan.put("napindan", 2.3);
        lowerBicutan.put("new lower bicutan", 2.0);
        lowerBicutan.put("north daang hari", 3.6);
        lowerBicutan.put("north signal village", 1.9);
        lowerBicutan.put("northside", 2.2);
        lowerBicutan.put("palingon", 0.4);
        lowerBicutan.put("pembo", 1.9);
        lowerBicutan.put("pinagsama", 0.7);
        lowerBicutan.put("pitogo", 0.5);
        lowerBicutan.put("rizal", 2.1);
        lowerBicutan.put("san miguel", 3.6);
        lowerBicutan.put("santa ana", 3.7);
        lowerBicutan.put("south cembo", 2.5);
        lowerBicutan.put("south daang hari", 1.5);
        lowerBicutan.put("south signal village", 1.1);
        lowerBicutan.put("southside", 1.3);
        lowerBicutan.put("tanyag", 2.9);
        lowerBicutan.put("tuktukan", 0.4);
        lowerBicutan.put("upper bicutan", 1.3);
        lowerBicutan.put("ususan", 2.1);
        lowerBicutan.put("wawa", 2.9);
        lowerBicutan.put("west rembo", 1.6);
        lowerBicutan.put("western bicutan", 2.4);
        DISTANCES.put("lower bicutan", lowerBicutan);
        // -------- MAHARLIKA VILLAGE --------
        Map<String, Double> maharlikaVillage = new HashMap<>();
        maharlikaVillage.put("bagumbayan", 4.0);
        maharlikaVillage.put("bambang", 2.5);
        maharlikaVillage.put("calzada", 2.0);
        maharlikaVillage.put("cembo", 4.3);
        maharlikaVillage.put("central bicutan", 2.9);
        maharlikaVillage.put("central signal village", 4.7);
        maharlikaVillage.put("comembo", 1.3);
        maharlikaVillage.put("east rembo", 1.9);
        maharlikaVillage.put("fort bonifacio", 2.4);
        maharlikaVillage.put("hagonoy", 1.3);
        maharlikaVillage.put("ibayo-tipas", 0.4);
        maharlikaVillage.put("katuparan", 1.9);
        maharlikaVillage.put("ligid-tipas", 3.2);
        maharlikaVillage.put("lower bicutan", 2.7);
        maharlikaVillage.put("maharlika village", 0.0);
        maharlikaVillage.put("napindan", 0.5);
        maharlikaVillage.put("new lower bicutan", 4.5);
        maharlikaVillage.put("north daang hari", 3.7);
        maharlikaVillage.put("north signal village", 1.3);
        maharlikaVillage.put("northside", 1.7);
        maharlikaVillage.put("palingon", 2.8);
        maharlikaVillage.put("pembo", 4.5);
        maharlikaVillage.put("pinagsama", 3.0);
        maharlikaVillage.put("pitogo", 2.4);
        maharlikaVillage.put("rizal", 0.6);
        maharlikaVillage.put("san miguel", 3.6);
        maharlikaVillage.put("santa ana", 4.0);
        maharlikaVillage.put("south cembo", 3.8);
        maharlikaVillage.put("south daang hari", 2.3);
        maharlikaVillage.put("south signal village", 2.7);
        maharlikaVillage.put("southside", 1.3);
        maharlikaVillage.put("tanyag", 1.7);
        maharlikaVillage.put("tuktukan", 2.5);
        maharlikaVillage.put("upper bicutan", 3.8);
        maharlikaVillage.put("ususan", 4.7);
        maharlikaVillage.put("wawa", 1.0);
        maharlikaVillage.put("west rembo", 4.2);
        maharlikaVillage.put("western bicutan", 3.0);
        DISTANCES.put("maharlika village", maharlikaVillage);
// -------- NAPINDAN --------
Map<String, Double> napindan = new HashMap<>();
napindan.put("bagumbayan", 3.5);
napindan.put("bambang", 1.9);
napindan.put("calzada", 2.0);
napindan.put("cembo", 3.9);
napindan.put("central bicutan", 2.3);
napindan.put("central signal village", 4.3);
napindan.put("comembo", 1.0);
napindan.put("east rembo", 1.9);
napindan.put("fort bonifacio", 2.0);
napindan.put("hagonoy", 0.9);
napindan.put("ibayo-tipas", 0.1);
napindan.put("katuparan", 1.6);
napindan.put("ligid-tipas", 2.7);
napindan.put("lower bicutan", 2.3);
napindan.put("maharlika village", 0.5);
napindan.put("napindan", 0.0);
napindan.put("new lower bicutan", 4.1);
napindan.put("north daang hari", 3.2);
napindan.put("north signal village", 1.4);
napindan.put("northside", 1.2);
napindan.put("palingon", 2.6);
napindan.put("pembo", 4.1);
napindan.put("pinagsama", 2.6);
napindan.put("pitogo", 2.0);
napindan.put("rizal", 0.3);
napindan.put("san miguel", 3.1);
napindan.put("santa ana", 3.5);
napindan.put("south cembo", 3.2);
napindan.put("south daang hari", 2.3);
napindan.put("south signal village", 2.6);
napindan.put("southside", 1.1);
napindan.put("tanyag", 1.3);
napindan.put("tuktukan", 2.2);
napindan.put("upper bicutan", 3.4);
napindan.put("ususan", 4.2);
napindan.put("wawa", 0.7);
napindan.put("west rembo", 3.9);
napindan.put("western bicutan", 2.4);
DISTANCES.put("napindan", napindan);
// -------- NEW LOWER BICUTAN --------
Map<String, Double> newLowerBicutan = new HashMap<>();
newLowerBicutan.put("bagumbayan", 1.4);
newLowerBicutan.put("bambang", 3.3);
newLowerBicutan.put("calzada", 3.4);
newLowerBicutan.put("cembo", 0.4);
newLowerBicutan.put("central bicutan", 2.6);
newLowerBicutan.put("central signal village", 0.2);
newLowerBicutan.put("comembo", 4.6);
newLowerBicutan.put("east rembo", 3.3);
newLowerBicutan.put("fort bonifacio", 2.1);
newLowerBicutan.put("hagonoy", 3.3);
newLowerBicutan.put("ibayo-tipas", 4.2);
newLowerBicutan.put("katuparan", 2.7);
newLowerBicutan.put("ligid-tipas", 1.9);
newLowerBicutan.put("lower bicutan", 2.0);
newLowerBicutan.put("maharlika village", 4.5);
newLowerBicutan.put("napindan", 4.1);
newLowerBicutan.put("new lower bicutan", 0.0);
newLowerBicutan.put("north daang hari", 4.0);
newLowerBicutan.put("north signal village", 3.8);
newLowerBicutan.put("northside", 3.5);
newLowerBicutan.put("palingon", 2.0);
newLowerBicutan.put("pembo", 0.2);
newLowerBicutan.put("pinagsama", 1.5);
newLowerBicutan.put("pitogo", 2.1);
newLowerBicutan.put("rizal", 3.9);
newLowerBicutan.put("san miguel", 4.1);
newLowerBicutan.put("santa ana", 3.9);
newLowerBicutan.put("south cembo", 2.4);
newLowerBicutan.put("south daang hari", 3.2);
newLowerBicutan.put("south signal village", 2.7);
newLowerBicutan.put("southside", 3.3);
newLowerBicutan.put("tanyag", 4.2);
newLowerBicutan.put("tuktukan", 2.0);
newLowerBicutan.put("upper bicutan", 0.7);
newLowerBicutan.put("ususan", 0.2);
newLowerBicutan.put("wawa", 4.5);
newLowerBicutan.put("west rembo", 0.6);
newLowerBicutan.put("western bicutan", 3.0);
DISTANCES.put("new lower bicutan", newLowerBicutan);
// -------- NORTH DAANG HARI --------
Map<String, Double> northDaangHari = new HashMap<>();
northDaangHari.put("bagumbayan", 2.7);
northDaangHari.put("bambang", 1.4);
northDaangHari.put("calzada", 4.6);
northDaangHari.put("cembo", 4.0);
northDaangHari.put("central bicutan", 1.7);
northDaangHari.put("central signal village", 4.2);
northDaangHari.put("comembo", 2.6);
northDaangHari.put("east rembo", 4.4);
northDaangHari.put("fort bonifacio", 3.2);
northDaangHari.put("hagonoy", 3.2);
northDaangHari.put("ibayo-tipas", 3.3);
northDaangHari.put("katuparan", 3.5);
northDaangHari.put("ligid-tipas", 2.3);
northDaangHari.put("lower bicutan", 3.6);
northDaangHari.put("maharlika village", 3.7);
northDaangHari.put("napindan", 3.2);
northDaangHari.put("new lower bicutan", 4.0);
northDaangHari.put("north daang hari", 0.0);
northDaangHari.put("north signal village", 4.2);
northDaangHari.put("northside", 2.0);
northDaangHari.put("palingon", 4.0);
northDaangHari.put("pembo", 4.1);
northDaangHari.put("pinagsama", 3.2);
northDaangHari.put("pitogo", 3.1);
northDaangHari.put("rizal", 3.3);
northDaangHari.put("san miguel", 0.1);
northDaangHari.put("santa ana", 0.4);
northDaangHari.put("south cembo", 1.7);
northDaangHari.put("south daang hari", 4.7);
northDaangHari.put("south signal village", 4.6);
northDaangHari.put("southside", 3.4);
northDaangHari.put("tanyag", 2.0);
northDaangHari.put("tuktukan", 3.2);
northDaangHari.put("upper bicutan", 3.7);
northDaangHari.put("ususan", 4.0);
northDaangHari.put("wawa", 2.8);
northDaangHari.put("west rembo", 4.2);
northDaangHari.put("western bicutan", 1.2);
DISTANCES.put("north daang hari", northDaangHari);
// -------- NORTH SIGNAL VILLAGE --------
Map<String, Double> northSignalVillage = new HashMap<>();
northSignalVillage.put("bagumbayan", 3.7);
northSignalVillage.put("bambang", 2.9);
northSignalVillage.put("calzada", 0.7);
northSignalVillage.put("cembo", 3.5);
northSignalVillage.put("central bicutan", 2.9);
northSignalVillage.put("central signal village", 4.0);
northSignalVillage.put("comembo", 2.4);
northSignalVillage.put("east rembo", 0.7);
northSignalVillage.put("fort bonifacio", 1.8);
northSignalVillage.put("hagonoy", 1.0);
northSignalVillage.put("ibayo-tipas", 1.4);
northSignalVillage.put("katuparan", 1.2);
northSignalVillage.put("ligid-tipas", 3.0);
northSignalVillage.put("lower bicutan", 1.9);
northSignalVillage.put("maharlika village", 1.3);
northSignalVillage.put("napindan", 1.4);
northSignalVillage.put("new lower bicutan", 3.8);
northSignalVillage.put("north daang hari", 4.2);
northSignalVillage.put("north signal village", 0.0);
northSignalVillage.put("northside", 2.2);
northSignalVillage.put("palingon", 1.9);
northSignalVillage.put("pembo", 3.7);
northSignalVillage.put("pinagsama", 2.4);
northSignalVillage.put("pitogo", 1.8);
northSignalVillage.put("rizal", 1.1);
northSignalVillage.put("san miguel", 4.1);
northSignalVillage.put("santa ana", 4.4);
northSignalVillage.put("south cembo", 3.8);
northSignalVillage.put("south daang hari", 1.0);
northSignalVillage.put("south signal village", 1.5);
northSignalVillage.put("southside", 0.8);
northSignalVillage.put("tanyag", 2.6);
northSignalVillage.put("tuktukan", 1.9);
northSignalVillage.put("upper bicutan", 3.1);
northSignalVillage.put("ususan", 4.0);
northSignalVillage.put("wawa", 2.1);
northSignalVillage.put("west rembo", 3.4);
northSignalVillage.put("western bicutan", 3.3);
DISTANCES.put("north signal village", northSignalVillage);
// -------- NORTHSIDE (POST PROPER NORTHSIDE) --------
Map<String, Double> northside = new HashMap<>();
northside.put("bagumbayan", 2.6);
northside.put("bambang", 0.7);
northside.put("calzada", 2.6);
northside.put("cembo", 3.3);
northside.put("central bicutan", 1.2);
northside.put("central signal village", 3.7);
northside.put("comembo", 1.2);
northside.put("east rembo", 2.5);
northside.put("fort bonifacio", 1.7);
northside.put("hagonoy", 1.3);
northside.put("ibayo-tipas", 1.3);
northside.put("katuparan", 1.8);
northside.put("ligid-tipas", 1.8);
northside.put("lower bicutan", 2.2);
northside.put("maharlika village", 1.7);
northside.put("napindan", 1.2);
northside.put("new lower bicutan", 3.5);
northside.put("north daang hari", 2.0);
northside.put("north signal village", 2.2);
northside.put("northside", 0.0);
northside.put("palingon", 2.5);
northside.put("pembo", 3.5);
northside.put("pinagsama", 2.1);
northside.put("pitogo", 1.7);
northside.put("rizal", 1.3);
northside.put("san miguel", 1.9);
northside.put("santa ana", 2.3);
northside.put("south cembo", 2.1);
northside.put("south daang hari", 2.8);
northside.put("south signal village", 2.9);
northside.put("southside", 1.5);
northside.put("tanyag", 0.7);
northside.put("tuktukan", 1.8);
northside.put("upper bicutan", 2.9);
northside.put("ususan", 3.6);
northside.put("wawa", 1.1);
northside.put("west rembo", 3.4);
northside.put("western bicutan", 1.2);
DISTANCES.put("northside", northside);
// -------- PALINGON --------
Map<String, Double> palingon = new HashMap<>();
palingon.put("bagumbayan", 2.3);
palingon.put("bambang", 2.7);
palingon.put("calzada", 1.5);
palingon.put("cembo", 1.6);
palingon.put("central bicutan", 2.3);
palingon.put("central signal village", 2.1);
palingon.put("comembo", 3.4);
palingon.put("east rembo", 1.4);
palingon.put("fort bonifacio", 0.8);
palingon.put("hagonoy", 1.6);
palingon.put("ibayo-tipas", 2.7);
palingon.put("katuparan", 0.9);
palingon.put("ligid-tipas", 1.9);
palingon.put("lower bicutan", 0.4);
palingon.put("maharlika village", 2.8);
palingon.put("napindan", 2.6);
palingon.put("new lower bicutan", 2.0);
palingon.put("north daang hari", 4.0);
palingon.put("north signal village", 1.9);
palingon.put("northside", 2.5);
palingon.put("palingon", 0.0);
palingon.put("pembo", 1.8);
palingon.put("pinagsama", 0.9);
palingon.put("pitogo", 0.8);
palingon.put("rizal", 2.3);
palingon.put("san miguel", 3.9);
palingon.put("santa ana", 4.0);
palingon.put("south cembo", 2.8);
palingon.put("south daang hari", 1.3);
palingon.put("south signal village", 0.8);
palingon.put("southside", 1.5);
palingon.put("tanyag", 3.2);
palingon.put("tuktukan", 0.7);
palingon.put("upper bicutan", 1.3);
palingon.put("ususan", 2.1);
palingon.put("wawa", 3.1);
palingon.put("west rembo", 1.5);
palingon.put("western bicutan", 2.8);
DISTANCES.put("palingon", palingon);
// -------- PEMBO --------
Map<String, Double> pembo = new HashMap<>();
pembo.put("bagumbayan", 1.5);
pembo.put("bambang", 3.4);
pembo.put("calzada", 3.3);
pembo.put("cembo", 0.2);
pembo.put("central bicutan", 2.7);
pembo.put("central signal village", 0.3);
pembo.put("comembo", 4.6);
pembo.put("east rembo", 3.2);
pembo.put("fort bonifacio", 2.0);
pembo.put("hagonoy", 3.2);
pembo.put("ibayo-tipas", 4.2);
pembo.put("katuparan", 2.6);
pembo.put("ligid-tipas", 1.9);
pembo.put("lower bicutan", 1.9);
pembo.put("maharlika village", 4.5);
pembo.put("napindan", 4.1);
pembo.put("new lower bicutan", 0.2);
pembo.put("north daang hari", 4.1);
pembo.put("north signal village", 3.7);
pembo.put("northside", 3.5);
pembo.put("palingon", 1.8);
pembo.put("pembo", 0.0);
pembo.put("pinagsama", 1.5);
pembo.put("pitogo", 2.1);
pembo.put("rizal", 3.9);
pembo.put("san miguel", 4.2);
pembo.put("santa ana", 4.0);
pembo.put("south cembo", 2.5);
pembo.put("south daang hari", 3.1);
pembo.put("south signal village", 2.5);
pembo.put("southside", 3.2);
pembo.put("tanyag", 4.2);
pembo.put("tuktukan", 1.9);
pembo.put("upper bicutan", 0.7);
pembo.put("ususan", 0.4);
pembo.put("wawa", 4.5);
pembo.put("west rembo", 0.4);
pembo.put("western bicutan", 3.1);
DISTANCES.put("pembo", pembo);
// -------- PINAGSAMA --------
Map<String, Double> pinagsama = new HashMap<>();
pinagsama.put("bagumbayan", 1.3);
pinagsama.put("bambang", 2.1);
pinagsama.put("calzada", 2.2);
pinagsama.put("cembo", 1.2);
pinagsama.put("central bicutan", 1.5);
pinagsama.put("central signal village", 1.7);
pinagsama.put("comembo", 3.2);
pinagsama.put("east rembo", 2.1);
pinagsama.put("fort bonifacio", 0.6);
pinagsama.put("hagonoy", 1.8);
pinagsama.put("ibayo-tipas", 2.7);
pinagsama.put("katuparan", 1.3);
pinagsama.put("ligid-tipas", 1.0);
pinagsama.put("lower bicutan", 0.7);
pinagsama.put("maharlika village", 3.0);
pinagsama.put("napindan", 2.6);
pinagsama.put("new lower bicutan", 1.5);
pinagsama.put("north daang hari", 3.2);
pinagsama.put("north signal village", 2.4);
pinagsama.put("northside", 2.1);
pinagsama.put("palingon", 0.9);
pinagsama.put("pembo", 1.5);
pinagsama.put("pinagsama", 0.0);
pinagsama.put("pitogo", 0.7);
pinagsama.put("rizal", 2.4);
pinagsama.put("san miguel", 3.2);
pinagsama.put("santa ana", 3.2);
pinagsama.put("south cembo", 1.9);
pinagsama.put("south daang hari", 2.1);
pinagsama.put("south signal village", 1.7);
pinagsama.put("southside", 1.8);
pinagsama.put("tanyag", 2.8);
pinagsama.put("tuktukan", 0.5);
pinagsama.put("upper bicutan", 0.8);
pinagsama.put("ususan", 1.6);
pinagsama.put("wawa", 3.0);
pinagsama.put("west rembo", 1.3);
pinagsama.put("western bicutan", 2.0);
DISTANCES.put("pinagsama", pinagsama);
// -------- PITOGO --------
Map<String, Double> pitogo = new HashMap<>();
pitogo.put("bagumbayan", 1.9);
pitogo.put("bambang", 1.9);
pitogo.put("calzada", 1.7);
pitogo.put("cembo", 1.9);
pitogo.put("central bicutan", 1.5);
pitogo.put("central signal village", 2.3);
pitogo.put("comembo", 2.7);
pitogo.put("east rembo", 1.6);
pitogo.put("fort bonifacio", 0.0);
pitogo.put("hagonoy", 1.1);
pitogo.put("ibayo-tipas", 2.1);
pitogo.put("katuparan", 0.7);
pitogo.put("ligid-tipas", 1.3);
pitogo.put("lower bicutan", 0.5);
pitogo.put("maharlika village", 2.4);
pitogo.put("napindan", 2.0);
pitogo.put("new lower bicutan", 2.1);
pitogo.put("north daang hari", 3.1);
pitogo.put("north signal village", 1.8);
pitogo.put("northside", 1.7);
pitogo.put("palingon", 0.8);
pitogo.put("pembo", 2.1);
pitogo.put("pinagsama", 0.7);
pitogo.put("pitogo", 0.0);
pitogo.put("rizal", 1.8);
pitogo.put("san miguel", 3.1);
pitogo.put("santa ana", 3.2);
pitogo.put("south cembo", 2.1);
pitogo.put("south daang hari", 1.7);
pitogo.put("south signal village", 1.4);
pitogo.put("southside", 1.1);
pitogo.put("tanyag", 2.4);
pitogo.put("tuktukan", 0.2);
pitogo.put("upper bicutan", 1.4);
pitogo.put("ususan", 2.3);
pitogo.put("wawa", 2.5);
pitogo.put("west rembo", 1.9);
pitogo.put("western bicutan", 2.0);
DISTANCES.put("pitogo", pitogo);
    // -------- RIZAL --------
Map<String, Double> rizal = new HashMap<>();
rizal.put("bagumbayan", 3.4);
rizal.put("bambang", 2.0);
rizal.put("calzada", 1.7);
rizal.put("cembo", 3.6);
rizal.put("central bicutan", 2.3);
rizal.put("central signal village", 4.1);
rizal.put("comembo", 1.3);
rizal.put("east rembo", 1.6);
rizal.put("fort bonifacio", 1.8);
rizal.put("hagonoy", 0.7);
rizal.put("ibayo-tipas", 0.3);
rizal.put("katuparan", 1.4);
rizal.put("ligid-tipas", 2.6);
rizal.put("lower bicutan", 2.1);
rizal.put("maharlika village", 0.6);
rizal.put("napindan", 0.3);
rizal.put("new lower bicutan", 3.9);
rizal.put("north daang hari", 3.3);
rizal.put("north signal village", 1.1);
rizal.put("northside", 1.3);
rizal.put("palingon", 2.3);
rizal.put("pembo", 3.9);
rizal.put("pinagsama", 2.4);
rizal.put("pitogo", 1.8);
rizal.put("rizal", 0.0);
rizal.put("san miguel", 3.2);
rizal.put("santa ana", 3.5);
rizal.put("south cembo", 3.2);
rizal.put("south daang hari", 2.0);
rizal.put("south signal village", 2.3);
rizal.put("southside", 0.8);
rizal.put("tanyag", 1.5);
rizal.put("tuktukan", 1.9);
rizal.put("upper bicutan", 3.2);
rizal.put("ususan", 4.0);
rizal.put("wawa", 1.0);
rizal.put("west rembo", 3.6);
rizal.put("western bicutan", 2.5);
DISTANCES.put("rizal", rizal);
// -------- SAN MIGUEL --------
Map<String, Double> sanMiguel = new HashMap<>();
sanMiguel.put("bagumbayan", 2.7);
sanMiguel.put("bambang", 1.3);
sanMiguel.put("calzada", 4.5);
sanMiguel.put("cembo", 4.1);
sanMiguel.put("central bicutan", 1.7);
sanMiguel.put("central signal village", 4.3);
sanMiguel.put("comembo", 2.5);
sanMiguel.put("east rembo", 4.3);
sanMiguel.put("fort bonifacio", 3.1);
sanMiguel.put("hagonoy", 3.2);
sanMiguel.put("ibayo-tipas", 3.2);
sanMiguel.put("katuparan", 3.5);
sanMiguel.put("ligid-tipas", 2.3);
sanMiguel.put("lower bicutan", 3.6);
sanMiguel.put("maharlika village", 3.6);
sanMiguel.put("napindan", 3.1);
sanMiguel.put("new lower bicutan", 4.1);
sanMiguel.put("north daang hari", 0.1);
sanMiguel.put("north signal village", 4.1);
sanMiguel.put("northside", 1.9);
sanMiguel.put("palingon", 3.9);
sanMiguel.put("pembo", 4.2);
sanMiguel.put("pinagsama", 3.2);
sanMiguel.put("pitogo", 3.1);
sanMiguel.put("rizal", 3.2);
sanMiguel.put("san miguel", 0.0);
sanMiguel.put("santa ana", 0.5);
sanMiguel.put("south cembo", 1.8);
sanMiguel.put("south daang hari", 4.6);
sanMiguel.put("south signal village", 4.5);
sanMiguel.put("southside", 3.4);
sanMiguel.put("tanyag", 1.9);
sanMiguel.put("tuktukan", 3.2);
sanMiguel.put("upper bicutan", 3.7);
sanMiguel.put("ususan", 4.1);
sanMiguel.put("wawa", 2.6);
sanMiguel.put("west rembo", 4.3);
sanMiguel.put("western bicutan", 1.2);
DISTANCES.put("san miguel", sanMiguel);
// -------- SANTA ANA --------
Map<String, Double> santaAna = new HashMap<>();
santaAna.put("bagumbayan", 2.5);
santaAna.put("bambang", 1.6);
santaAna.put("calzada", 4.7);
santaAna.put("cembo", 3.9);
santaAna.put("central bicutan", 1.7);
santaAna.put("central signal village", 4.1);
santaAna.put("comembo", 3.0);
santaAna.put("east rembo", 4.5);
santaAna.put("fort bonifacio", 3.2);
santaAna.put("hagonoy", 3.4);
santaAna.put("ibayo-tipas", 3.6);
santaAna.put("katuparan", 3.7);
santaAna.put("ligid-tipas", 2.2);
santaAna.put("lower bicutan", 3.7);
santaAna.put("maharlika village", 4.0);
santaAna.put("napindan", 3.5);
santaAna.put("new lower bicutan", 3.9);
santaAna.put("north daang hari", 0.4);
santaAna.put("north signal village", 4.4);
santaAna.put("northside", 2.3);
santaAna.put("palingon", 4.0);
santaAna.put("pembo", 4.0);
santaAna.put("pinagsama", 3.2);
santaAna.put("pitogo", 3.2);
santaAna.put("rizal", 3.5);
santaAna.put("san miguel", 0.5);
santaAna.put("santa ana", 0.0);
santaAna.put("south cembo", 1.5);
santaAna.put("south daang hari", 4.8);
santaAna.put("south signal village", 4.7);
santaAna.put("southside", 3.6);
santaAna.put("tanyag", 2.4);
santaAna.put("tuktukan", 3.3);
santaAna.put("upper bicutan", 3.6);
santaAna.put("ususan", 3.8);
santaAna.put("wawa", 3.1);
santaAna.put("west rembo", 4.1);
santaAna.put("western bicutan", 1.3);
DISTANCES.put("santa ana", santaAna);
// -------- SOUTH CEMBO --------
Map<String, Double> southCembo = new HashMap<>();
southCembo.put("bagumbayan", 1.0);
southCembo.put("bambang", 1.5);
southCembo.put("calzada", 3.8);
southCembo.put("cembo", 2.4);
southCembo.put("central bicutan", 0.9);
southCembo.put("central signal village", 2.6);
southCembo.put("comembo", 3.2);
southCembo.put("east rembo", 3.7);
southCembo.put("fort bonifacio", 2.1);
southCembo.put("hagonoy", 2.8);
southCembo.put("ibayo-tipas", 3.4);
southCembo.put("katuparan", 2.8);
southCembo.put("ligid-tipas", 0.9);
southCembo.put("lower bicutan", 2.5);
southCembo.put("maharlika village", 3.8);
southCembo.put("napindan", 3.2);
southCembo.put("new lower bicutan", 2.4);
southCembo.put("north daang hari", 1.7);
southCembo.put("north signal village", 3.8);
southCembo.put("northside", 2.1);
southCembo.put("palingon", 2.8);
southCembo.put("pembo", 2.5);
southCembo.put("pinagsama", 1.9);
southCembo.put("pitogo", 2.1);
southCembo.put("rizal", 3.2);
southCembo.put("san miguel", 1.8);
southCembo.put("santa ana", 1.5);
southCembo.put("south cembo", 0.0);
southCembo.put("south daang hari", 3.9);
southCembo.put("south signal village", 3.5);
southCembo.put("southside", 3.0);
southCembo.put("tanyag", 2.6);
southCembo.put("tuktukan", 2.2);
southCembo.put("upper bicutan", 2.1);
southCembo.put("ususan", 2.3);
southCembo.put("wawa", 3.2);
southCembo.put("west rembo", 2.7);
southCembo.put("western bicutan", 1.0);
DISTANCES.put("south cembo", southCembo);
// -------- SOUTH DAANG HARI --------
Map<String, Double> southDaangHari = new HashMap<>();
southDaangHari.put("bagumbayan", 3.5);
southDaangHari.put("bambang", 3.3);
southDaangHari.put("calzada", 0.3);
southDaangHari.put("cembo", 2.9);
southDaangHari.put("central bicutan", 3.2);
southDaangHari.put("central signal village", 3.4);
southDaangHari.put("comembo", 3.3);
southDaangHari.put("east rembo", 0.4);
southDaangHari.put("fort bonifacio", 1.7);
southDaangHari.put("hagonoy", 1.6);
southDaangHari.put("ibayo-tipas", 2.3);
southDaangHari.put("katuparan", 1.2);
southDaangHari.put("ligid-tipas", 3.0);
southDaangHari.put("lower bicutan", 1.5);
southDaangHari.put("maharlika village", 2.3);
southDaangHari.put("napindan", 2.3);
southDaangHari.put("new lower bicutan", 3.2);
southDaangHari.put("north daang hari", 4.7);
southDaangHari.put("north signal village", 1.0);
southDaangHari.put("northside", 2.8);
southDaangHari.put("palingon", 1.3);
southDaangHari.put("pembo", 3.1);
southDaangHari.put("pinagsama", 2.1);
southDaangHari.put("pitogo", 1.7);
southDaangHari.put("rizal", 2.0);
southDaangHari.put("san miguel", 4.6);
southDaangHari.put("santa ana", 4.8);
southDaangHari.put("south cembo", 3.9);
southDaangHari.put("south daang hari", 0.0);
southDaangHari.put("south signal village", 0.6);
southDaangHari.put("southside", 1.4);
southDaangHari.put("tanyag", 3.3);
southDaangHari.put("tuktukan", 1.7);
southDaangHari.put("upper bicutan", 2.6);
southDaangHari.put("ususan", 3.4);
southDaangHari.put("wawa", 3.0);
southDaangHari.put("west rembo", 2.7);
southDaangHari.put("western bicutan", 3.6);
DISTANCES.put("south daang hari", southDaangHari);
// -------- SOUTH SIGNAL VILLAGE --------
Map<String, Double> southSignalVillage = new HashMap<>();
southSignalVillage.put("bagumbayan", 3.1);
southSignalVillage.put("bambang", 3.3);
southSignalVillage.put("calzada", 0.9);
southSignalVillage.put("cembo", 2.3);
southSignalVillage.put("central bicutan", 3.0);
southSignalVillage.put("central signal village", 2.8);
southSignalVillage.put("comembo", 3.5);
southSignalVillage.put("east rembo", 0.9);
southSignalVillage.put("fort bonifacio", 1.4);
southSignalVillage.put("hagonoy", 1.7);
southSignalVillage.put("ibayo-tipas", 2.6);
southSignalVillage.put("katuparan", 1.1);
southSignalVillage.put("ligid-tipas", 2.7);
southSignalVillage.put("lower bicutan", 1.1);
southSignalVillage.put("maharlika village", 2.7);
southSignalVillage.put("napindan", 2.6);
southSignalVillage.put("new lower bicutan", 2.7);
southSignalVillage.put("north daang hari", 4.6);
southSignalVillage.put("north signal village", 1.5);
southSignalVillage.put("northside", 2.9);
southSignalVillage.put("palingon", 0.8);
southSignalVillage.put("pembo", 2.5);
southSignalVillage.put("pinagsama", 1.7);
southSignalVillage.put("pitogo", 1.4);
southSignalVillage.put("rizal", 2.3);
southSignalVillage.put("san miguel", 4.5);
southSignalVillage.put("santa ana", 4.7);
southSignalVillage.put("south cembo", 3.5);
southSignalVillage.put("south daang hari", 0.6);
southSignalVillage.put("south signal village", 0.0);
southSignalVillage.put("southside", 1.5);
southSignalVillage.put("tanyag", 3.5);
southSignalVillage.put("tuktukan", 1.4);
southSignalVillage.put("upper bicutan", 2.1);
southSignalVillage.put("ususan", 2.9);
southSignalVillage.put("wawa", 3.3);
southSignalVillage.put("west rembo", 2.1);
southSignalVillage.put("western bicutan", 3.4);
DISTANCES.put("south signal village", southSignalVillage);
// -------- SOUTHSIDE (POST PROPER SOUTHSIDE) --------
Map<String, Double> southside = new HashMap<>();
southside.put("bagumbayan", 2.9);
southside.put("bambang", 2.1);
southside.put("calzada", 1.1);
southside.put("cembo", 3.0);
southside.put("central bicutan", 2.1);
southside.put("central signal village", 3.4);
southside.put("comembo", 2.0);
southside.put("east rembo", 1.0);
southside.put("fort bonifacio", 1.2);
southside.put("hagonoy", 0.2);
southside.put("ibayo-tipas", 1.1);
southside.put("katuparan", 0.6);
southside.put("ligid-tipas", 2.2);
southside.put("lower bicutan", 1.3);
southside.put("maharlika village", 1.3);
southside.put("napindan", 1.1);
southside.put("new lower bicutan", 3.3);
southside.put("north daang hari", 3.4);
southside.put("north signal village", 0.8);
southside.put("northside", 1.5);
southside.put("palingon", 1.5);
southside.put("pembo", 3.2);
southside.put("pinagsama", 1.8);
southside.put("pitogo", 1.1);
southside.put("rizal", 0.8);
southside.put("san miguel", 3.4);
southside.put("santa ana", 3.6);
southside.put("south cembo", 3.0);
southside.put("south daang hari", 1.4);
southside.put("south signal village", 1.5);
southside.put("southside", 0.0);
southside.put("tanyag", 2.0);
southside.put("tuktukan", 1.3);
southside.put("upper bicutan", 2.5);
southside.put("ususan", 3.4);
southside.put("wawa", 1.7);
southside.put("west rembo", 2.9);
southside.put("western bicutan", 2.4);
DISTANCES.put("southside", southside);
// -------- TANYAG --------
Map<String, Double> tanyag = new HashMap<>();
tanyag.put("bagumbayan", 3.3);
tanyag.put("bambang", 1.1);
tanyag.put("calzada", 3.1);
tanyag.put("cembo", 4.1);
tanyag.put("central bicutan", 1.8);
tanyag.put("central signal village", 4.4);
tanyag.put("comembo", 0.6);
tanyag.put("east rembo", 3.0);
tanyag.put("fort bonifacio", 2.4);
tanyag.put("hagonoy", 1.8);
tanyag.put("ibayo-tipas", 1.3);
tanyag.put("katuparan", 2.4);
tanyag.put("ligid-tipas", 2.5);
tanyag.put("lower bicutan", 2.9);
tanyag.put("maharlika village", 1.7);
tanyag.put("napindan", 1.3);
tanyag.put("new lower bicutan", 4.2);
tanyag.put("north daang hari", 2.0);
tanyag.put("north signal village", 2.6);
tanyag.put("northside", 0.7);
tanyag.put("palingon", 3.2);
tanyag.put("pembo", 4.2);
tanyag.put("pinagsama", 2.8);
tanyag.put("pitogo", 2.4);
tanyag.put("rizal", 1.5);
tanyag.put("san miguel", 1.9);
tanyag.put("santa ana", 2.4);
tanyag.put("south cembo", 2.6);
tanyag.put("south daang hari", 3.3);
tanyag.put("south signal village", 3.5);
tanyag.put("southside", 2.0);
tanyag.put("tanyag", 0.0);
tanyag.put("tuktukan", 2.6);
tanyag.put("upper bicutan", 3.6);
tanyag.put("ususan", 4.3);
tanyag.put("wawa", 0.7);
tanyag.put("west rembo", 4.1);
tanyag.put("western bicutan", 1.7);
DISTANCES.put("tanyag", tanyag);
// -------- TUKTUKAN --------
Map<String, Double> tuktukan = new HashMap<>();
tuktukan.put("bagumbayan", 1.8);
tuktukan.put("bambang", 2.0);
tuktukan.put("calzada", 1.8);
tuktukan.put("cembo", 1.7);
tuktukan.put("central bicutan", 1.6);
tuktukan.put("central signal village", 2.2);
tuktukan.put("comembo", 2.8);
tuktukan.put("east rembo", 1.6);
tuktukan.put("fort bonifacio", 0.1);
tuktukan.put("hagonoy", 1.3);
tuktukan.put("ibayo-tipas", 2.3);
tuktukan.put("katuparan", 0.8);
tuktukan.put("ligid-tipas", 1.3);
tuktukan.put("lower bicutan", 0.4);
tuktukan.put("maharlika village", 2.5);
tuktukan.put("napindan", 2.2);
tuktukan.put("new lower bicutan", 2.0);
tuktukan.put("north daang hari", 3.2);
tuktukan.put("north signal village", 1.9);
tuktukan.put("northside", 1.8);
tuktukan.put("palingon", 0.7);
tuktukan.put("pembo", 1.9);
tuktukan.put("pinagsama", 0.5);
tuktukan.put("pitogo", 0.2);
tuktukan.put("rizal", 1.9);
tuktukan.put("san miguel", 3.2);
tuktukan.put("santa ana", 3.3);
tuktukan.put("south cembo", 2.2);
tuktukan.put("south daang hari", 1.7);
tuktukan.put("south signal village", 1.4);
tuktukan.put("southside", 1.3);
tuktukan.put("tanyag", 2.6);
tuktukan.put("tuktukan", 0.0);
tuktukan.put("upper bicutan", 1.3);
tuktukan.put("ususan", 2.1);
tuktukan.put("wawa", 2.6);
tuktukan.put("west rembo", 1.7);
tuktukan.put("western bicutan", 2.0);
DISTANCES.put("tuktukan", tuktukan);
// -------- UPPER BICUTAN --------
Map<String, Double> upperBicutan = new HashMap<>();
upperBicutan.put("bagumbayan", 1.2);
upperBicutan.put("bambang", 2.8);
upperBicutan.put("calzada", 2.8);
upperBicutan.put("cembo", 0.5);
upperBicutan.put("central bicutan", 2.1);
upperBicutan.put("central signal village", 0.9);
upperBicutan.put("comembo", 4.0);
upperBicutan.put("east rembo", 2.7);
upperBicutan.put("fort bonifacio", 1.4);
upperBicutan.put("hagonoy", 2.6);
upperBicutan.put("ibayo-tipas", 3.5);
upperBicutan.put("katuparan", 2.0);
upperBicutan.put("ligid-tipas", 1.4);
upperBicutan.put("lower bicutan", 1.3);
upperBicutan.put("maharlika village", 3.8);
upperBicutan.put("napindan", 3.4);
upperBicutan.put("new lower bicutan", 0.7);
upperBicutan.put("north daang hari", 3.7);
upperBicutan.put("north signal village", 3.1);
upperBicutan.put("northside", 2.9);
upperBicutan.put("palingon", 1.3);
upperBicutan.put("pembo", 0.7);
upperBicutan.put("pinagsama", 0.8);
upperBicutan.put("pitogo", 1.4);
upperBicutan.put("rizal", 3.2);
upperBicutan.put("san miguel", 3.7);
upperBicutan.put("santa ana", 3.6);
upperBicutan.put("south cembo", 2.1);
upperBicutan.put("south daang hari", 2.6);
upperBicutan.put("south signal village", 2.1);
upperBicutan.put("southside", 2.5);
upperBicutan.put("tanyag", 3.6);
upperBicutan.put("tuktukan", 1.3);
upperBicutan.put("upper bicutan", 0.0);
upperBicutan.put("ususan", 0.8);
upperBicutan.put("wawa", 3.8);
upperBicutan.put("west rembo", 0.6);
upperBicutan.put("western bicutan", 2.5);
DISTANCES.put("upper bicutan", upperBicutan);
// -------- USUSAN --------
Map<String, Double> ususan = new HashMap<>();
ususan.put("bagumbayan", 1.3);
ususan.put("bambang", 3.4);
ususan.put("calzada", 3.6);
ususan.put("cembo", 0.5);
ususan.put("central bicutan", 2.6);
ususan.put("central signal village", 0.2);
ususan.put("comembo", 4.7);
ususan.put("east rembo", 3.5);
ususan.put("fort bonifacio", 2.2);
ususan.put("hagonoy", 3.4);
ususan.put("ibayo-tipas", 4.4);
ususan.put("katuparan", 2.8);
ususan.put("ligid-tipas", 1.9);
ususan.put("lower bicutan", 2.1);
ususan.put("maharlika village", 4.7);
ususan.put("napindan", 4.2);
ususan.put("new lower bicutan", 0.2);
ususan.put("north daang hari", 4.0);
ususan.put("north signal village", 4.0);
ususan.put("northside", 3.6);
ususan.put("palingon", 2.1);
ususan.put("pembo", 0.4);
ususan.put("pinagsama", 1.6);
ususan.put("pitogo", 2.3);
ususan.put("rizal", 4.0);
ususan.put("san miguel", 4.1);
ususan.put("santa ana", 3.8);
ususan.put("south cembo", 2.3);
ususan.put("south daang hari", 3.4);
ususan.put("south signal village", 2.9);
ususan.put("southside", 3.4);
ususan.put("tanyag", 4.3);
ususan.put("tuktukan", 2.1);
ususan.put("upper bicutan", 0.8);
ususan.put("ususan", 0.0);
ususan.put("wawa", 4.6);
ususan.put("west rembo", 0.8);
ususan.put("western bicutan", 3.0);
DISTANCES.put("ususan", ususan);
// -------- WAWA --------
Map<String, Double> wawa = new HashMap<>();
wawa.put("bagumbayan", 3.7);
wawa.put("bambang", 1.7);
wawa.put("calzada", 2.7);
wawa.put("cembo", 4.3);
wawa.put("central bicutan", 2.3);
wawa.put("central signal village", 4.7);
wawa.put("comembo", 0.3);
wawa.put("east rembo", 2.6);
wawa.put("fort bonifacio", 2.5);
wawa.put("hagonoy", 1.6);
wawa.put("ibayo-tipas", 0.8);
wawa.put("katuparan", 2.2);
wawa.put("ligid-tipas", 2.9);
wawa.put("lower bicutan", 2.9);
wawa.put("maharlika village", 1.0);
wawa.put("napindan", 0.7);
wawa.put("new lower bicutan", 4.5);
wawa.put("north daang hari", 2.8);
wawa.put("north signal village", 2.1);
wawa.put("northside", 1.1);
wawa.put("palingon", 3.1);
wawa.put("pembo", 4.5);
wawa.put("pinagsama", 3.0);
wawa.put("pitogo", 2.5);
wawa.put("rizal", 1.0);
wawa.put("san miguel", 2.6);
wawa.put("santa ana", 3.1);
wawa.put("south cembo", 3.2);
wawa.put("south daang hari", 3.0);
wawa.put("south signal village", 3.3);
wawa.put("southside", 1.7);
wawa.put("tanyag", 0.7);
wawa.put("tuktukan", 2.6);
wawa.put("upper bicutan", 3.8);
wawa.put("ususan", 4.6);
wawa.put("wawa", 0.0);
wawa.put("west rembo", 4.3);
wawa.put("western bicutan", 2.3);
DISTANCES.put("wawa", wawa);
// -------- WEST REMBO --------
Map<String, Double> westRembo = new HashMap<>();
westRembo.put("bagumbayan", 1.7);
westRembo.put("bambang", 3.3);
westRembo.put("calzada", 2.9);
westRembo.put("cembo", 0.3);
westRembo.put("central bicutan", 2.7);
westRembo.put("central signal village", 0.7);
westRembo.put("comembo", 4.5);
westRembo.put("east rembo", 2.8);
westRembo.put("fort bonifacio", 1.8);
westRembo.put("hagonoy", 2.9);
westRembo.put("ibayo-tipas", 4.0);
westRembo.put("katuparan", 2.3);
westRembo.put("ligid-tipas", 2.0);
westRembo.put("lower bicutan", 1.6);
westRembo.put("maharlika village", 4.2);
westRembo.put("napindan", 3.9);
westRembo.put("new lower bicutan", 0.6);
westRembo.put("north daang hari", 4.2);
westRembo.put("north signal village", 3.4);
westRembo.put("northside", 3.4);
westRembo.put("palingon", 1.5);
westRembo.put("pembo", 0.4);
westRembo.put("pinagsama", 1.3);
westRembo.put("pitogo", 1.9);
westRembo.put("rizal", 3.6);
westRembo.put("san miguel", 4.3);
westRembo.put("santa ana", 4.1);
westRembo.put("south cembo", 2.7);
westRembo.put("south daang hari", 2.7);
westRembo.put("south signal village", 2.1);
westRembo.put("southside", 2.9);
westRembo.put("tanyag", 4.1);
westRembo.put("tuktukan", 1.7);
westRembo.put("upper bicutan", 0.6);
westRembo.put("ususan", 0.8);
westRembo.put("wawa", 4.3);
westRembo.put("west rembo", 0.0);
westRembo.put("western bicutan", 3.1);
DISTANCES.put("west rembo", westRembo);
// -------- WESTERN BICUTAN --------
Map<String, Double> westernBicutan = new HashMap<>();
westernBicutan.put("bagumbayan", 1.8);
westernBicutan.put("bambang",0.6);
westernBicutan.put("calzada",3.5);
westernBicutan.put("cembo",2.9);
westernBicutan.put("central bicutan",0.5);
westernBicutan.put("central signal village",3.2);
westernBicutan.put("comembo",2.3);
westernBicutan.put("east rembo",3.3);
westernBicutan.put("fort bonifacio",2.0);
westernBicutan.put("hagonoy",2.2);
westernBicutan.put("ibayo-tipas",2.6);
westernBicutan.put("katuparan",2.4);
westernBicutan.put("ligid-tipas",1.1);
westernBicutan.put("lower bicutan",1.0);
westernBicutan.put("maharlika village",3.0);
westernBicutan.put("napindan", 2.4);
westernBicutan.put("new lower bicutan",3.0);
westernBicutan.put("north daang hari",1.2);
westernBicutan.put("north signal village",3.3);
westernBicutan.put("northside",1.2);
westernBicutan.put("palingon",2.8);
westernBicutan.put("pembo",3.1);
westernBicutan.put("pinagsama",2.0);
westernBicutan.put("pitogo", 2.0);
westernBicutan.put("rizal",2.5);
westernBicutan.put("san miguel",1.2);
westernBicutan.put("santa ana",1.3);
westernBicutan.put("south cembo",1.0);
westernBicutan.put("south daang hari",3.6);
westernBicutan.put("south signal village", 3.4);
westernBicutan.put("southside", 2.4);
westernBicutan.put("tanyag",1.7);
westernBicutan.put("tuktukan",2.0);
westernBicutan.put("upper bicutan",2.5);
westernBicutan.put("ususan",3.0);
westernBicutan.put("wawa",2.3);
westernBicutan.put("west rembo",3.1);
westernBicutan.put("western bicutan",0.0);
DISTANCES.put("western bicutan", westernBicutan);
    }
    // Method to get distance between two barangays
    private static DistanceResult getDistance(String pickup, String dropoff) {
        DistanceResult result = new DistanceResult();

        if (pickup == null || dropoff == null) {
            result.validRoute = false;
            return result;
        }

        Map<String, Double> dropoffs = DISTANCES.get(pickup.toLowerCase());
        if (dropoffs != null) {
            Double distance = dropoffs.get(dropoff.toLowerCase());
            if (distance != null) {
                result.distance = distance;
                result.validRoute = true;
                return result;
            }
        }
        result.validRoute = false;
        return result;
    }
    public static void main(String[] args) {
        Scanner TV = new Scanner(System.in);
        String regUsername = "";
        String regPassword = "";
        String loginUsername;
        String loginPassword;
        // ------------------- Registration/Login -------------------
        System.out.println("=== TODA SYSTEM ===");
        System.out.println("1 - Register");
        System.out.println("2 - Login");
        System.out.print("Choose option: ");
        int option = TV.nextInt();
        TV.nextLine();

        switch (option) {
            case 1:
                System.out.print("Create username: ");
                regUsername = TV.nextLine();
                System.out.print("Create password: ");
                regPassword = TV.nextLine();
                System.out.println("Registration successful! Please login.");
                while (true) {
                    System.out.print("Enter username: ");
                    loginUsername = TV.nextLine();
                    System.out.print("Enter password: ");
                    loginPassword = TV.nextLine();
                    if (loginUsername.equals(regUsername) && loginPassword.equals(regPassword)) {
                        System.out.println("Login successful! Welcome, " + regUsername + ".");
                        break;
                    } else {
                        System.out.println("Wrong username or password. Try again.\n");
                    }
                }
                break;
            case 2:
                if (regUsername.equals("")) {
                    System.out.println("No account found. Please register first.");
                    System.out.print("Create username: ");
                    regUsername = TV.nextLine();
                    System.out.print("Create password: ");
                    regPassword = TV.nextLine();
                    System.out.println("Registration successful!");
                }
                while (true) {
                    System.out.print("Enter username: ");
                    loginUsername = TV.nextLine();
                    System.out.print("Enter password: ");
                    loginPassword = TV.nextLine();
                    if (loginUsername.equals(regUsername) && loginPassword.equals(regPassword)) {
                        System.out.println("Login successful! Welcome Operator.");
                        break;
                    } else {
                        System.out.println("Wrong username or password. Try again.\n");
                    }
                }
                break;
            default:
                System.out.println("Invalid option.");
                TV.close();
                return;
        }
        // ------------------- Passenger Type -------------------
        while(true) {
        int passengerType;
        do {
            System.out.println("Input type of Passenger:");
            System.out.println("0 - Exit Program/Finish for the day");
            System.out.println("1 - Regular");
            System.out.println("2 - Student (20% discount)");
            System.out.println("3 - Senior Citizen (20% discount)");
            System.out.println("4 - PWD (20% discount)");
            System.out.println("5 - Pregnant Women (20% discount)");
            System.out.println("6 - Solo Parent (20% discount)");
            System.out.print("Input: ");

            while (!TV.hasNextInt()) {
                System.out.println("Invalid input. Please enter a number between 0 and 6.");
                TV.next();
                System.out.print("Input: ");
            }

            passengerType = TV.nextInt();
            if (passengerType == 0) {
                System.out.println("Exiting program.");
                TV.close();
                return;
            }
            if (passengerType < 1 || passengerType > 6) {
                System.out.println("Invalid Passenger Type. Kindly input the correct passenger (or 0 to quit).");
            } else {
                break;
            }
        } while (true);

        switch(passengerType) {
            case 1: System.out.println("Regular Passenger. No discount."); break;
            case 2: case 3: case 4: case 5: case 6:
                System.out.println("Discounted Passenger. 20% discount applied."); break;
        }

        // ------------------- Number of Passengers -------------------
        int numPassengers;
        do {
            System.out.print("Enter number of passengers (1-4, or 0 to quit): ");
            while (!TV.hasNextInt()) {
                System.out.println("Invalid input. Please enter a numeric value.");
                TV.next();
                System.out.print("Enter number of passengers (1-4, or 0 to quit): ");
            }
            numPassengers = TV.nextInt();
            if (numPassengers == 0) {
                System.out.println("Exiting program.");
                TV.close();
                return;
            }
            if (numPassengers < 1 || numPassengers > 4) {
                System.out.println("Invalid number of passengers. Please enter between 1 and 4.");
            } else break;
        } while (true);

        // ------------------- Fare Calculation -------------------
        double fare;
        boolean hasDiscount = passengerType >= 2 && passengerType <= 6;
        if (numPassengers == 1) fare = hasDiscount ? 10.0 : 30.0;
        else fare = hasDiscount ? 10.0 * numPassengers : 12.0 * numPassengers;
        System.out.println("Initial Fare: " + fare + " Pesos");

        // ------------------- Pickup/Dropoff -------------------
        TV.nextLine(); // consume leftover newline
        System.out.println("Enter pickup location (Barangay you are currently in): ");
        String pickupLocation = TV.nextLine().toLowerCase();
        System.out.println("Enter drop-off location (Barangay passenger wants to go to): ");
        String dropoffLocation = TV.nextLine().toLowerCase();

        DistanceResult result = getDistance(pickupLocation, dropoffLocation);
        double distance = result.distance;
        boolean validRoute = result.validRoute;

        if (validRoute) {
            double distanceFare = Math.ceil(distance);
            double totalFare = fare + distanceFare;
            System.out.println("================================");
            System.out.println("Driver Name: " + regUsername);
            System.out.println("Passenger Type: " + passengerType);
            System.out.println("Number of Passengers: " + numPassengers); 
            System.out.println("Pickup Location: " + pickupLocation);
            System.out.println("Dropoff Location: " + dropoffLocation);
            System.out.println("================================");
            System.out.println("Base Fare: " + fare + " Pesos");
            System.out.println("Distance: " + distance + " km");
            System.out.println("Distance Fare: " + distanceFare + " Pesos");
            System.out.println("Total Fare: " + totalFare + " Pesos");
            System.out.println("Thank you for using our service.");
            System.out.println("================================");
        } else {
            System.out.println("Invalid route. Please check barangay names.");
            continue;
            }
        } 
        
    }
}
